language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "stable"
  - "8"
  - "6"
install: yarn

branches:
  only:
    - master
script:
  - yarn install
  - yarn run test
  - tsc
before_deploy: # 在 发布之前, 执行命令(按照实际情况调整)
  - cd dist
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true # 为了防止 Travis CI 清理额外的文件夹并删除你做的改变