language: node_js

node_js:
  - "stable"
  - "8"
  - "6"
cache: yarn # 使用 yarn 而不是 npm (按照实际情况调整)
install: yarn

branches:
  only:
    - master
before_script:
  - yarn install
  - yarn run test

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
